---
abstract: 'The great new Bio::Parser::ISATab!'
author:
  - 'Bob MacCallum <r.maccallum@imperial.ac.uk>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Parser-ISATab
provides:
  Bio::Parser::ISATab:
    file: lib/Bio/Parser/ISATab.pm
    version: 0.01
requires:
  Text::CSV_XS: 1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
